### ISSUE TITLE
Conduct Kickoff meeting

### ISSUE THREAD

**Issue by vr00n** [argo-marketplace/RadRoads#1]
Discuss project with registered contributors.
- Introductions and Context.
- Answer any questions.
- Review [dirt simple project spec](https://github.com/argo-marketplace/test-project/blob/master/README.md)
- Assign the following roles:
   - `SCRIBE`: During a project, this SOLVER role will be responsible for maintaining project notes, minutes and ensuring documentation is up to date. This role will need to be filled during Project Kickoff meeting and can be revolved every so often.

   - `OPS`: During a project, this SOLVER role will be responsible for ensuring schedules and that the team is able to communicate without issue. The person under this role will organize meetings/conference-calls/hangouts as necessary. This role will need to be filled during Project Kickoff meeting and can be revolved every so often.

**Comment by jazzzchan** [comment]
Yu- I can take the OPS role.

**Comment by nnhoucheng** [comment]
I will take the SCRIBE role.

**Comment by ywnch** [comment]
I will assist with the OPS role (and SCRIBE as needed).
