### ISSUE TITLE
Meeting 1/20 

### ISSUE THREAD

**Issue by jazzzchan** [argo-marketplace/RadRoads#10]
## Meeting 1/20 agenda

- Questions regarding the exploration of arcGIS "sinuosity"
- Next Step: 
  1. polish notebooks
  2. combine notebooks

# How to submit an issue?

- [x] Have you checked previously open/closed issues to see if your question has already been asked & addressed? 
  - If there is an open issue similar to your issue. Comment on that open issue with additional detail indicating that you too are having the same issue. This allows the project sponsor to prioritize incoming issues.
- [x] Have you provided a clear description of your issue so that the project sponsor is able to answer all your questions with as few back-n-forths as possible?
- [x] _(Please acknowledge by checking this box)_ If a screenshot or visual helps better communicate some complex idea, have you provided one?. [Draw.io](Draw.io), [Lucidchart](www.lucidchart.com), and [Autodraw](www.autodraw.com) are some excellent and quick drawing tools.
- [x] _(Please acknowledge by checking this box)_ When an issue is resolved, please post the steps to resolution or clearly describe the resolution before marking the issue closed. 
   - This will help future `SOLVERS` read through how your issue was solved and may help them solve their issue quicker.
- [x] Have you been kind, courteous, and considerate in your questions? 
- [x] Have you considered using `Stackedit.io`, a handy tool to quickly write in markdown?

**Comment by jazzzchan** [comment]
meeting postponed
notebook will be uploaded later

**Comment by vr00n** [comment]
Hi folks. Any update on these ?

**Comment by jazzzchan** [comment]
I am working with Yuwen Chang on the final merged notebook. 

@nnhoucheng Please find more updates and discussion in the group chat. Thanks:)

**Comment by ywnch** [comment]
Just updated a prototype for circuity calculation, not meaningful enough yet, but works!

**Comment by jazzzchan** [comment]
notebooks have been updated but worth more polish
