### ISSUE TITLE
Consolidating RadRoads

### ISSUE THREAD

**Issue by vr00n** [argo-marketplace/RadRoads#14]
Hi everyone - I'm looking for a summary from someone on how an outside user can implement RadRoads? 

I see many notebooks here but have no clear idea on how to implement RadRoads on some city.

My recommendation is to consolidate the work into a single python file and provide a `requirements.txt` so that any user can git clone this repo and input a city name and get RadRoad outputs:

Example:

```
git clone RadRoads repo
cd RadRoads
python RadRoads.py Tempe, AZ
RadRoads Output for Tempe, AZ
Top 5 longest roads
Top 5 curviest Roads
Top 5 Straightest Roads
```

A stretch goal could be to provide a single python notebook to illustrate plotting techniques using RadRoads outputs. 

Thanks

# How to submit an issue?

- [x] Have you checked previously open/closed issues to see if your question has already been asked & addressed? 
  - If there is an open issue similar to your issue. Comment on that open issue with additional detail indicating that you too are having the same issue. This allows the project sponsor to prioritize incoming issues.
- [x] Have you provided a clear description of your issue so that the project sponsor is able to answer all your questions with as few back-n-forths as possible?
- [x] _(Please acknowledge by checking this box)_ If a screenshot or visual helps better communicate some complex idea, have you provided one?. [Draw.io](Draw.io), [Lucidchart](www.lucidchart.com), and [Autodraw](www.autodraw.com) are some excellent and quick drawing tools.
- [x] _(Please acknowledge by checking this box)_ When an issue is resolved, please post the steps to resolution or clearly describe the resolution before marking the issue closed. 
   - This will help future `SOLVERS` read through how your issue was solved and may help them solve their issue quicker.
- [x] Have you been kind, courteous, and considerate in your questions? 
- [x] Have you considered using `Stackedit.io`, a handy tool to quickly write in markdown?

**Comment by vr00n** [comment]
Also im not able to find whether `sinuosity` is being used to determine curviest / straightest roads. Can someone tell me what the plan is here?

**Comment by jazzzchan** [comment]
Answering the sinuosity, I think our methodology for curviness now actually is the sinuosity methodology. We imported the Vincenty and devided that by the straight distance which is exactly the function of sinuosity. Are you looking for the "sinuosity" as keyword or..?

**Comment by jazzzchan** [comment]
to expand more, vincenty is the geographical distance , so by dividing the straight distance, we conduct the curviness

**Comment by jazzzchan** [comment]
for circuity, it is the difference between two nodes and divided by the straight distance, which i don't think it's what we are doing? Please correct me if my understanding was wrong.

**Comment by vr00n** [comment]
Thanks @jazzzchan can you please create a new issue for discussing approaches to Straight/Curvy roads? ...and how do you feel about this issue (consolidating to a single script). Can it be done? Thanks!

**Comment by ywnch** [comment]
I think I had a paragraph discussing the concept of sinuousity and how it is adopted in terms of roads (instead of rivers). Please let me know if you think we should elaborate more on that part.

I think we will be working on wrapping up the current stage of work throughout next week. I think there are still some calibrations to do.

I would say, in future work, the definition of curviness may have more than one indicators as different curviness measures can mean different things, as discussed in the article.

**Comment by vr00n** [comment]
@ywnch please refer #15 for curviness discussion.

Once you consolidate `functions_basic.ipynb` to a .py file - we can close this issue

THANK YOU!
