### ISSUE TITLE
Curviness calculation method

### ISSUE THREAD

**Issue by jazzzchan** [argo-marketplace/RadRoads#15]
Two concept to calculate Curviness: 

**- Circuity** 

Circuity measures the difference between measured route length and geometric distance between two places ( calculated as the difference between measured route length and geometric distance
divided by the measured route distance). It is more efficient when comes to straighter routes. Therefore, this method is less applicable in our scenario. 

**- Sinuosity (sinuosity index, or sinuosity coefficient)**  - Our approach 

Sinuosity allows the calculation of a continuously differentiable curve by having its ratio of curvilinear length (along the curve) and the Euclidean distance (straight line) between the end points of the curve. This dimensionless quantity can also be rephrased as the "actual path length" divided by the "shortest path length" of a curve. The value ranges from 1 (case of straight line) to infinity (case of a closed loop, where the shortest path length is zero) or for an infinitely-long actual path.
For our case, we adopted this method because this method is really significant when the line is continuously differentiable (no angular point). Simply by importing "vincenty" from Geopy, this python package allows us to conduct the distance between points on an ellipsoidal earth model. Then divide the road street (distance between two nodes) by the vincenty distance, we receive sinuosity of the road. 

# How to submit an issue?

- [x] Have you checked previously open/closed issues to see if your question has already been asked & addressed? 
  - If there is an open issue similar to your issue. Comment on that open issue with additional detail indicating that you too are having the same issue. This allows the project sponsor to prioritize incoming issues.
- [x] Have you provided a clear description of your issue so that the project sponsor is able to answer all your questions with as few back-n-forths as possible?
- [x] _(Please acknowledge by checking this box)_ If a screenshot or visual helps better communicate some complex idea, have you provided one?. [Draw.io](Draw.io), [Lucidchart](www.lucidchart.com), and [Autodraw](www.autodraw.com) are some excellent and quick drawing tools.
- [x] _(Please acknowledge by checking this box)_ When an issue is resolved, please post the steps to resolution or clearly describe the resolution before marking the issue closed. 
   - This will help future `SOLVERS` read through how your issue was solved and may help them solve their issue quicker.
- [x] Have you been kind, courteous, and considerate in your questions? 
- [x] Have you considered using `Stackedit.io`, a handy tool to quickly write in markdown?

**Comment by jazzzchan** [comment]
please feel free to edit the paragraph :)

**Comment by vr00n** [comment]
I agree re: Circuity - so lets forget about that. Thank you.

re: Sinuosity - I don't understand the need for vincenty. Vincenty calculates the accurate distance assuming the earth's natural curvature but for streets - the earth's natural curvature is negligible (i.e. earth's curvature tends to zero for short distances like streets).

Can we please update `function_basic` to use `compute_sinuosity (gdf)` based on code available here please?
https://github.com/Geosyntec/gisutils/blob/a4034d5dfed472588548306860d010b3dd99a980/gisutils/algo.py

..and lets rename any references to `circuity` to `sinuosity`

THANK YOU!!!

**Comment by ywnch** [comment]
No problem, thank you, Varun! I will get back here tonight or tomorrow.
