### ISSUE TITLE
radroads.py: first compilation

### ISSUE THREAD

**Issue by ywnch** [argo-marketplace/RadRoads#16]
A [python script](https://github.com/argo-marketplace/RadRoads/blob/master/notebooks/radroads.py) and a [demo nb](https://github.com/argo-marketplace/RadRoads/blob/master/notebooks/demo_radroads.ipynb) has been created, please try it out and pose bugs or improvements here.
The script can definitely use some code optimization to be made more concise at this point.

# How to submit an issue?

- [x] Have you checked previously open/closed issues to see if your question has already been asked & addressed? 
  - If there is an open issue similar to your issue. Comment on that open issue with additional detail indicating that you too are having the same issue. This allows the project sponsor to prioritize incoming issues.
- [x] Have you provided a clear description of your issue so that the project sponsor is able to answer all your questions with as few back-n-forths as possible?
- [x] _(Please acknowledge by checking this box)_ If a screenshot or visual helps better communicate some complex idea, have you provided one?. [Draw.io](Draw.io), [Lucidchart](www.lucidchart.com), and [Autodraw](www.autodraw.com) are some excellent and quick drawing tools.
- [x] _(Please acknowledge by checking this box)_ When an issue is resolved, please post the steps to resolution or clearly describe the resolution before marking the issue closed. 
   - This will help future `SOLVERS` read through how your issue was solved and may help them solve their issue quicker.
- [x] Have you been kind, courteous, and considerate in your questions? 
- [x] Have you considered using `Stackedit.io`, a handy tool to quickly write in markdown?

**Comment by vr00n** [comment]
This works perfectly and code is wonderfully documented. Kudos !
