### ISSUE TITLE
Meeting 12/30

### ISSUE THREAD

**Issue by vr00n** [argo-marketplace/RadRoads#3]
Hi there. We seem to be meeting tomorrow but I have not seen any updates to the repo.

@jazzzchan  (OPS) - Please prepare a brief agenda for tomorrow's meeting.
@ywnch @nnhoucheng doesn't seem to have accepted the invite link to this repo. (SCRIBE) Please update this issue with notes during the meeting

Thanks and looking fwd.

Varun

# How to submit an issue?

- [x] Have you checked previously open/closed issues to see if your question has already been asked & addressed? 
  - If there is an open issue similar to your issue. Comment on that open issue with additional detail indicating that you too are having the same issue. This allows the project sponsor to prioritize incoming issues.
- [x] Have you provided a clear description of your issue so that the project sponsor is able to answer all your questions with as few back-n-forths as possible?
- [x] _(Please acknowledge by checking this box)_ If a screenshot or visual helps better communicate some complex idea, have you provided one?. [Draw.io](Draw.io), [Lucidchart](www.lucidchart.com), and [Autodraw](www.autodraw.com) are some excellent and quick drawing tools.
- [x] _(Please acknowledge by checking this box)_ When an issue is resolved, please post the steps to resolution or clearly describe the resolution before marking the issue closed. 
   - This will help future `SOLVERS` read through how your issue was solved and may help them solve their issue quicker.
- [x] Have you been kind, courteous, and considerate in your questions? 
- [x] Have you considered using `Stackedit.io`, a handy tool to quickly write in markdown?

**Comment by jazzzchan** [comment]
hey, sorry my bad. the agenda has been updated, please refer to the newest issue, and please make corrections and/or edits for more thoughts on tomorrow's meeting.

**Comment by ywnch** [comment]
@vr00n Should future meeting notes go in issue comments or markdowns in a repo folder?

**Comment by ywnch** [comment]
I think it works this way:
Each meeting will be created as an issue, staring with agenda and (possibly) ending with meeting notes and conclusions/decisions. Is that right?
If so, @jazzzchan you might move the agenda here later.

**Comment by ywnch** [comment]
## 12/30/2017 Second Meeting Agenda
- introduce adding python notebook to the repo and how to work on one notebook as a team
- review Nominatim (if necessary)
- answer questions
- determine milestone (next step) for each city given the hypothesis that we want to find the best roads to plan Autonomous vehicle pilots in the following cities (new york, Boulder, LA)

**Comment by ywnch** [comment]
## 12/30/2017 City Assignment
1. LA: @nnhoucheng 
2. NYC: @ywnch
3. Boulder: @jazzzchan

**Comment by ywnch** [comment]
## 12/30/2017 Tasks
- Open issues (e.g., Nominatim API, query for polygons)
- Start with a neighborhood as a sandbox
- Work on #2 (longest, shortest, curviest, straightest)

**Comment by jazzzchan** [comment]
## Jan.6 Meeting Agenda: 

- Review Open Street Map Data Model: 
https://www.mapbox.com/mapping/osm-data-model/
http://wiki.openstreetmap.org/wiki/Elements
- Questions regarding Open Street Map Data Model.
- Review Milestone1: the Longest Street in Each City 
- * is it possible to generate OSM relation for the neighborhood?*
