### ISSUE TITLE
2nd meeting agenda

### ISSUE THREAD

**Issue by jazzzchan** [argo-marketplace/RadRoads#4]
- introduce adding python notebook to the repo and how to work on one notebook as a team

- review Nominatim (if necessary)

- answer questions

- determine milestone (next step) for each city given the hypothesis that we want to find the best roads to plan Autonomous vehicle pilots in the following cities (new york, Boulder, LA)

# How to submit an issue?

- [x] Have you checked previously open/closed issues to see if your question has already been asked & addressed? 
  - If there is an open issue similar to your issue. Comment on that open issue with additional detail indicating that you too are having the same issue. This allows the project sponsor to prioritize incoming issues.
- [x] Have you provided a clear description of your issue so that the project sponsor is able to answer all your questions with as few back-n-forths as possible?
- [x] _(Please acknowledge by checking this box)_ If a screenshot or visual helps better communicate some complex idea, have you provided one?. [Draw.io](Draw.io), [Lucidchart](www.lucidchart.com), and [Autodraw](www.autodraw.com) are some excellent and quick drawing tools.
- [x] _(Please acknowledge by checking this box)_ When an issue is resolved, please post the steps to resolution or clearly describe the resolution before marking the issue closed. 
   - This will help future `SOLVERS` read through how your issue was solved and may help them solve their issue quicker.
- [x] Have you been kind, courteous, and considerate in your questions? 
- [x] Have you considered using `Stackedit.io`, a handy tool to quickly write in markdown?

**Comment by ywnch** [comment]
Moved to #3
