### ISSUE TITLE
Find street names

### ISSUE THREAD

**Issue by jazzzchan** [argo-marketplace/RadRoads#5]
- Streets that OSMnx maps out are in segment (block/nodes) form of per street. How do we define which segments belong to one street? I.E how do we tell which segment is the beginning of Houston St and which is the end?

- How can we give street names/ geographical information to each street that we have found? Or how can we find street names in order to define which segments belong to which street? 

# How to submit an issue?

- [x] Have you checked previously open/closed issues to see if your question has already been asked & addressed? 
  - If there is an open issue similar to your issue. Comment on that open issue with additional detail indicating that you too are having the same issue. This allows the project sponsor to prioritize incoming issues.
- [x] Have you provided a clear description of your issue so that the project sponsor is able to answer all your questions with as few back-n-forths as possible?
- [x] _(Please acknowledge by checking this box)_ If a screenshot or visual helps better communicate some complex idea, have you provided one?. [Draw.io](Draw.io), [Lucidchart](www.lucidchart.com), and [Autodraw](www.autodraw.com) are some excellent and quick drawing tools.
- [x] _(Please acknowledge by checking this box)_ When an issue is resolved, please post the steps to resolution or clearly describe the resolution before marking the issue closed. 
   - This will help future `SOLVERS` read through how your issue was solved and may help them solve their issue quicker.
- [x] Have you been kind, courteous, and considerate in your questions? 
- [x] Have you considered using `Stackedit.io`, a handy tool to quickly write in markdown?

**Comment by vr00n** [comment]
Hmm @jazzzchan can you please provide more detail for this? The description as it stands does not seem clear.

**Comment by jazzzchan** [comment]
https://github.com/openstreetmap/Nominatim/issues/377 
this issue looks relevant to our problem

**Comment by ywnch** [comment]
Current solution in the [nyc sandbox](https://github.com/argo-marketplace/RadRoads/blob/master/notebooks/longroad_nyc_sandbox.ipynb) is to group them back together in a dataframe. This introduces some problems to be discussed further.

**Comment by vr00n** [comment]
Great question.

We discussed this in length during #9

Beginning and End are relative terms. It depends on which direction you look at the map  (North, South, East West) OR if a street is one-way where the direction is enforced already.

- Indexing based on Name and From-To Nodes
- Example used: https://www.openstreetmap.org/way/260042856#map=17/40.01316/-105.28674&layers=D

OSM contains `Node` information for every `Way` and this can be used to identify, spatially,  the street segments.


I also asked everyone to check out 
https://github.com/Streets-Data-Collaborative/geo-street-talk-global and speak with Yukun Van about how you can combine methods from there and use here.
