### ISSUE TITLE
Why Nominatim searches show points and not polygons?

### ISSUE THREAD

**Issue by jazzzchan** [argo-marketplace/RadRoads#6]
- Find neighborhoods only return polygon not points. 
    - eg: East Village is returning as a point, Beijing is returning both point and polygon

# How to submit an issue?

- [x] Have you checked previously open/closed issues to see if your question has already been asked & addressed? 
  - If there is an open issue similar to your issue. Comment on that open issue with additional detail indicating that you too are having the same issue. This allows the project sponsor to prioritize incoming issues.
- [x] Have you provided a clear description of your issue so that the project sponsor is able to answer all your questions with as few back-n-forths as possible?
- [x] _(Please acknowledge by checking this box)_ If a screenshot or visual helps better communicate some complex idea, have you provided one?. [Draw.io](Draw.io), [Lucidchart](www.lucidchart.com), and [Autodraw](www.autodraw.com) are some excellent and quick drawing tools.
- [x] _(Please acknowledge by checking this box)_ When an issue is resolved, please post the steps to resolution or clearly describe the resolution before marking the issue closed. 
   - This will help future `SOLVERS` read through how your issue was solved and may help them solve their issue quicker.
- [x] Have you been kind, courteous, and considerate in your questions? 
- [x] Have you considered using `Stackedit.io`, a handy tool to quickly write in markdown?

**Comment by vr00n** [comment]
When I search for Beijing in Nominatim, i get 2 results

![image](https://user-images.githubusercontent.com/4397663/34470537-2e568f44-ef01-11e7-87a6-45ba9e41c398.png)


1. Beijing (city) and represented as an `OSM node`: http://www.openstreetmap.org/node/25248662

2. Beijing (State) and represented as an `OSM relation`: http://www.openstreetmap.org/relation/912940

This is important to understand as it involves the `Open Street Map Data Model` and is explained in detail here: 

- https://www.mapbox.com/mapping/osm-data-model/
- http://wiki.openstreetmap.org/wiki/Elements

@jazzzchan @ywnch @nnhoucheng please ensure you all read these links and lets discuss on next call (`OPS`, add to agenda for Jan-6 meeting)

**Comment by vr00n** [comment]
In the case for East Village, there is only an `OSM node` and no `OSM relation`. 
http://nominatim.openstreetmap.org/search.php?q=east+village+new+york&polygon_geojson=1&viewbox=

....that is because no one has actually created an `OSM relation` entry for NYC neighborhoods! (great future project!) and that is why you do not get a polygon. 

However, someone has created an  `OSM relation` entry for Manhattan Community Board 3. 

So in OSMnx, if you enter "Manhattan Community Board 3", you will get a polygon (please test this @jazzzchan ).

**Comment by jazzzchan** [comment]
a relationship needs to be created in order for OSMnx to plot the graph.
