### ISSUE TITLE
Meeting 1/6

### ISSUE THREAD

**Issue by vr00n** [argo-marketplace/RadRoads#7]
Hey @jazzzchan @nnhoucheng @ywnch,  Unfortunately I am not feeling very well and will not be able to join the call tomorrow. 

Can you please discuss amongst yourselves and post meeting minutes here for me to review later?

Please keep up the pace and good work!

**Comment by ywnch** [comment]
## Jan/06/2018 Meeting Agenda:

- Review Open Street Map Data Model: 
https://www.mapbox.com/mapping/osm-data-model/
http://wiki.openstreetmap.org/wiki/Elements
- Questions regarding Open Street Map Data Model and past task.
- Review Milestone1: the Longest Street in Each City 
- [ is it possible to generate OSM relation for the neighborhood? ]
- Next Milestone 2: Straightest and Curviest Street in Each City

**Comment by nnhoucheng** [comment]
## Jan/06/2018 Meeting Minutes:

- Discuss and summarize the skills to use the osmnx package and the openstreetmap nominatim API. We are still getting familiar with that.

- Discuss about the possible errors and outliers in the sandbox model.
Ourlier: 1. The longest and shortest street may turn out to be  highways, if we set our potential client to 
                 be autonomous cars, it's less feasible to test autonomous cars on highways.
             2. Our current "groupby" method has loopholes: it may combine two different streets with 
                 same name into one street. The length will be inaccurate. 

- Raise the question about the definitions: how to define the curviness of a street? 
- Previous question leads to another question: who's the audience for this project? Different client may affect our definition for curviness of the street. 

- Before next week's task: 
1. improve street length notebook 
2. work on the straightest and curviest street for each city. (city assignment will remain the same)
3. Think about the potential audience for this project. - autonomous cars? -routing service? -...?

**Comment by vr00n** [comment]
@nnhoucheng Thank you for the minutes!

@ywnch @jazzzchan Absolutely love the notebooks that you have uploaded! This is great progress!

@nnhoucheng perhaps you can combine approaches from @ywnch & @jazzzchan and create a sample notebook to find longest/shortest for LA!

I will think deeper on the questions you have posed in the meeting minutes and we will address all of these on our Jan 13th meeting!

We are very fortunate to have you guys on-board for this!
