### ISSUE TITLE
Curviest Street Definition

### ISSUE THREAD

**Issue by jazzzchan** [argo-marketplace/RadRoads#8]
How to define the curviness of a street? 
1. Based on the total quantity of curves(turns)
2. Based on maximum angle of turns on the street

i.e :  one street has multiple turns and the total number of turns are 90 degree VS. one street has only one 90 degree turn.  Which one is curvier? 

# How to submit an issue?

- [x] Have you checked previously open/closed issues to see if your question has already been asked & addressed? 
  - If there is an open issue similar to your issue. Comment on that open issue with additional detail indicating that you too are having the same issue. This allows the project sponsor to prioritize incoming issues.
- [x] Have you provided a clear description of your issue so that the project sponsor is able to answer all your questions with as few back-n-forths as possible?
- [x] _(Please acknowledge by checking this box)_ If a screenshot or visual helps better communicate some complex idea, have you provided one?. [Draw.io](Draw.io), [Lucidchart](www.lucidchart.com), and [Autodraw](www.autodraw.com) are some excellent and quick drawing tools.
- [x] _(Please acknowledge by checking this box)_ When an issue is resolved, please post the steps to resolution or clearly describe the resolution before marking the issue closed. 
   - This will help future `SOLVERS` read through how your issue was solved and may help them solve their issue quicker.
- [x] Have you been kind, courteous, and considerate in your questions? 
- [x] Have you considered using `Stackedit.io`, a handy tool to quickly write in markdown?

**Comment by ywnch** [comment]
probably have to refer to what bigger questions we want to ask, and by whom

**Comment by vr00n** [comment]
Please refer to these 

https://papers.ssrn.com/sol3/papers.cfm?abstract_id=3012678

And search for "circuity" in OSMnx reference docs.
