### ISSUE TITLE
Meeting 1/13

### ISSUE THREAD

**Issue by jazzzchan** [argo-marketplace/RadRoads#9]
## Meeting 1/13 Agenda:
- Review past notebooks and tasks[Longest, Shortest, Straightest, Curviest]

- Answer/discuss questions 

- Discuss ideas regarding this project's goal and how/what we can do to improve it

**Comment by ywnch** [comment]
Hi all,
I am traveling this week so may not be able to attend the meeting. Please proceed without me and I will catch up. Thanks!

**Comment by jazzzchan** [comment]
## Meeting 1/13 Minutes
- Improvements on current (longest/shortest) notebook: 
  1. Insert Google map interactive window 
  2. Colorize each street type (http://geoffboeing.com/2016/11/osmnx-python-street-networks/)


- Questions been touched/answered: 
   1. [Longest/Shortest] Avoid 'Motorway' in our outcome? --  Refer Hou Cheng's notebook for grouping by each street's highway type.
   2. [Longest/Shortest] Determine if one street is one way? -- Divide one street into 100 nodes and reverse check if they have same street name 
   3. [Longest/Shortest] How to differentiate two streets with same name? -- Add new street index besides street name: OSM nodes from, OSM nodes to. i.e: Street name OSM nodes from-OSM nodes to (#5 )
   4. [Straightest/Curviest] google" sinuosity"

- Next Milestons:
  1. Curviest/Straightest
  2. Polish all the notebooks
